# For a supported GitHub Pages theme:
theme: jekyll-theme-architect

# Add these for basic site info:
title: Cyber Security Picks
description: Simple cybersecurity buying guides for families, students, freelancers, and home users.
